apiVersion: v1
kind: PersistentVolume
metadata:
  name: chatbot-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/chatbot-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chatbot-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: chatbot-pv
